# Utiliser une image de base PHP avec extensions requises
FROM php:8.1-fpm

# Installer des dépendances
RUN apt-get update && apt-get install -y \
    libpq-dev \
    libzip-dev \
    unzip \
    git \
    && docker-php-ext-install pdo pdo_pgsql zip

# Installer Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Définir le répertoire de travail
WORKDIR /var/www/html

# Copier le fichier composer et installer les dépendances
COPY composer.json composer.lock ./
RUN composer install --prefer-dist --no-scripts --no-dev --no-autoloader

# Copier tout le contenu du projet
COPY . .

# Exposer le port 9000 et démarrer le serveur PHP-FPM
EXPOSE 9000
CMD ["php-fpm"]
